//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int DoctorID { get; set; }
        public string DoctorName { get; set; }
        public string DoctorSection { get; set; }
        public string DoctorPhoneNumber { get; set; }
        public int DoctorAge { get; set; }
        public string DoctorImage { get; set; }
        public string DoctorAddress { get; set; }
    }
}
