//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int PatientID { get; set; }
        public string PatientName { get; set; }
        public string PatientPhoneNumber { get; set; }
        public string PatientDisease { get; set; }
        public string PatientEmail { get; set; }
        public string PatientAddress { get; set; }
        public string PatientImage { get; set; }
        public string PatientDate { get; set; }
        public int PatientAmount { get; set; }
    }
}
